name: Build
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - 'build.sh'
      - scripts/**'
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [
          "linux_x86_64 linux",
          "linux_i386 linux",
          "win_amd64 windows",
          "win32 windows"
        ]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install --upgrade wheel
      - name: Build wheel
        run: python ./pack.py ${{ matrix.platform }}
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}